services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mkk_moon_task_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/mkk_moon_task_db
volumes:
  pgdata: